s3:
  access_key_id: AKIAIL5LTKXQ5S3VBUKQ
  secret_access_key: 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
disqus_identifier_prefix: ''
email:
  from: toolbot@thetoolbox.org
  to: info@thetoolbox.org
gaq: UA-38041239-1